apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:community
          ports:
            - containerPort: 7474
              name: browser
            - containerPort: 7687
              name: bolt
          env:
            - name: NEO4J_AUTH
              value: "neo4j/test1234"
            - name: NEO4J_dbms_memory_heap_initial__size
              value: "1G"
            - name: NEO4J_dbms_memory_heap_max__size
              value: "1G"
            - name: NEO4J_dbms_memory_pagecache_size
              value: "1G"
            - name: NEO4J_dbms_default__listen__address
              value: "0.0.0.0"
          volumeMounts:
            - name: neo4j-data
              mountPath: /data
          resources:
            requests:
              memory: "3Gi"
              cpu: "1"
            limits:
              memory: "3Gi"
              cpu: "2"
      volumes:
        - name: neo4j-data
          persistentVolumeClaim:
            claimName: neo4j-data-pvc
